apiVersion: apps/v1
kind: Deployment
metada:
  name: platfroms-deploy
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: platformservice
    template:
      metadata: 
        labels: 
          app: platformservice
      spec:
        containers: 
          - name: platformservice
            image: platformservice:latest
